export type Deal = {
  id: number;
  title: string;
  url: string;
  priceCad: number | null;
  shippingCad: number | null;
  totalPriceCad: number | null;
  totalUsd: number | null;
  historicPriceCad: number | null;
  discountPercent: number | null;
  sampleSize: number | null;
  historicSampleCount?: number | null;
  historicBaselineBucketUsed?: string | null;
  historicBaselineConfidence?: "high" | "medium" | "low" | "none";
  confidenceWeight?: number | null;
  market: string;
  endsAt: string | null;
  updatedAt: string | null;
  thumbnailUrl: string | null;
  stockImageUrl?: string | null; // TCGplayer stock image
  sellerUsername: string | null;
  sellerStoreName?: string | null;
  sellerFeedbackCount?: number | null;
  sellerPositivePercent?: number | null;
  card: {
    id: number;
    name: string | null;
    setName: string | null;
    cardNumber: string | null;
    conditionBucket: string | null;
  } | null;
  condition: string | null;
  setName: string | null;
  cardName: string | null;
  cardId: number | null;
  listingId?: string | null;
  integrityStatus?: "OK" | "REVIEW";
  integrityReason?: string | null;
  integrityScore?: number | null;
  overrideType?: "ALLOW" | "HARD_BLOCK" | "SOFT_EXCLUDE";
};
